spring:
  application:
    name: taka-spring

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taka?serverTimezone=Asia/Seoul
    username: root
    password: Peniel102!

  mail:
    host: smtp.gmail.com
    port: 587
    username: k9wdev
    password: ffiletbgvzalrnrc
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  jwt:
    secret: kasdjflkjafjwoeijrowjflasdkjflaskjdflkajfslflkajsd
